# Generated by Django 4.0.4 on 2023-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckanAPI', '0002_alter_sts2020tocurrent_analysis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sts2020tocurrent',
            name='method_detection_limit',
            field=models.SmallIntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sts2020tocurrent',
            name='project',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sts2020tocurrent',
            name='reporting_limit',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sts2020tocurrent',
            name='result',
            field=models.BigIntegerField(null=True),
        ),
    ]
