# Generated by Django 4.0.4 on 2023-02-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckanAPI', '0003_sts2020tocurrent_method_detection_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sts2020tocurrent',
            name='method_detection_limit',
            field=models.SmallIntegerField(null=True),
        ),
    ]
