# Generated by Django 4.0.4 on 2023-02-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckanAPI', '0004_alter_sts2020tocurrent_method_detection_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sts2020tocurrent',
            name='reporting_limit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
